version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: ${APP_CONTAINER}
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  db:
    build: .docker/postgres
    container_name: ${DB_CONTAINER}
    restart: always
    tty: true
    ports:
      - "7000:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PGADMIN_CONTAINER}
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - db
